# Generated by Django 4.2.1 on 2023-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('position', models.CharField(max_length=16, null=True)),
                ('email', models.TextField(max_length=50, null=True)),
                ('describe', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Consult',
            },
        ),
    ]
